Improve error messages for missing response/request parts
icarus-consulting/Yaapii.Http pull request #75
Opened 2021-01-15 15:14 UTC by DFU398

### Please check if the PR fulfills these requirements
- [x] I made sure that my code builds (VisualStudio & cake script: build.ps1)
- [x] I merged the master into this branch before pushing
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### What is the current behavior? (You can also link to an open issue here)

### What is the new behavior?

closes #49 

### Does this PR introduce a breaking change? (check one with "x")
- [ ] Yes
- [x] No

### If this PR contains a breaking change, please describe the impact and migration path for existing applications

###  Other information

2021-01-19 08:06 UTC, Meerownymous requested changes
You could improve code by using FallbackMap instead of Fail objects.

2021-01-19 08:06 UTC, Meerownymous commented on src/Yaapii.Http/Parts/Bodies/TextBody.Of.cs
> +                    new FailWhen(
You could use the FallbackMap from Atoms - it would be more OO because it is an object which validates while using it.

2021-01-19 08:06 UTC, Meerownymous commented on src/Yaapii.Http/Parts/Headers/Accept.FirstOf.cs
> +//Copyright(c) 2020 ICARUS Consulting GmbH
```suggestion
//Copyright(c) 2021 ICARUS Consulting GmbH
```

2021-01-19 08:06 UTC, Meerownymous commented on src/Yaapii.Http/Parts/Headers/Authorization.FirstOf.cs
> +                    new InvalidOperationException($"Failed to extract first value of '{Authorization.KEY}' header. No values found.")
I think it would be more understandable to write 'Cannot find 'Authorization.KEY' in headers' - from the outside this is less technical.

2021-01-19 08:06 UTC, Meerownymous commented on src/Yaapii.Http/Parts/Method.Of.cs
> +                new FailWhen(
FallbackMap could also be used here.

2021-02-04 12:59 UTC, MSE1188 approved these changes

2021-02-04 13:03 UTC, merged